### PR TITLE
Fix error in senior_pointer_first

### PR DESCRIPTION
**Pull request by ashelkovnykov**
courtesy of @joemfb. The stuff of nightmares.

### CODE REVIEW

**Comment by drbeefsupreme** [comment]
I went back to checked to see that, indeed, I had this dereferenced correctly in an earlier iteration. I think, at least on the commit I'm checking, that lead straight into another more trivial bug that I probably then assumed that meant I was wrong to dereference.

Applying this fix, I am running into the following when trying out the Zorp jamfile that I unfortunately cannot share:

```
Program received signal SIGSEGV, Segmentation fault.
ares::mem::senior_pointer_first<ares::noun::CellMemory> (stack=0x7fffffffdb10, a=0x7ffff76e5398, b=0x7ffff7b73830) at src/mem.rs:840
840	                       low_pointer = *(frame_pointer.add(STACK)) as *const T;
(gdb) bt 10
#0  ares::mem::senior_pointer_first<ares::noun::CellMemory> (stack=0x7fffffffdb10, a=0x7ffff76e5398, b=0x7ffff7b73830) at src/mem.rs:840
#1  ares::mem::unifying_equality (stack=0x7fffffffdb10, a=0x7fffffffd8d8, b=0x7ffff59e7ff0) at src/mem.rs:758
#2  0x00005555555637eb in ares::hamt::MutHamt<u64>::lookup<u64> (self=..., stack=0x7fffffffdb10, n=0x7fffffffd8d8) at src/hamt.rs:86
#3  ares::serialization::jam (stack=0x7fffffffdb10, noun=...) at src/serialization.rs:181
#4  0x000055555556210d in ares::main () at src/main.rs:59
```

Its happening after the entire program has finished running and jamming the result. @eamsden said he thought he knew what this bug was. I think when I wrote https://github.com/urbit/ares/pull/98/commits/fa8853367868a527e583e49df75123c44db846a4#diff-f448d9b4f98ccd8f7b00d2f139831735dc0f66dad1e700b81248b3243ec4b255L824-L826 was supposed to catch this but I suppose not.

I noticed in the debugging session that you had changed the "previous" frame pointers for the initial frame https://github.com/urbit/ares/pull/98/commits/fa8853367868a527e583e49df75123c44db846a4#diff-f448d9b4f98ccd8f7b00d2f139831735dc0f66dad1e700b81248b3243ec4b255L73-L75 maybe that helps address this?

**Review by joemfb — APPROVED** [review]
this looks right to me, with both fixes that we discussed.

I still think that `senior_pointer_first()` should not be polymorphic, and only accept and return `*const u64`. But that could be saved for other refactoring ...

**Comment by joemfb** [comment]
@drbeefsupreme I think you should try again now, this PR didn't originally have the corrected null pointer checks.

**Comment by joemfb** [comment]
Strike all that, see #100.

**Comment by eamsden** [comment]
#100 puts the null check in the correct place. I didn't see this PR, sorry to dup work...

**Comment by eamsden** [comment]
Closing in favor of #100

**Comment by ashelkovnykov** [comment]
Petition to reopen pull request:
1. #100 is missing the `Cargo.toml` convenience-line w/ `assert_no_alloc` disabled
2. #100 is missing the safer `NockStack` initialization
3. Current code is not correct when the top-most stack is also the root stack (see below). The pointer `null` checks are required.

```
 lo=0x7fd35c000018 hi=0x7fd35c000018 f=0x7fd35ffffee0 s=0x7fd35ffffed0 a=0x7fd35c000018
 lo=0x7fd35ffffef8 hi=0x0 f=0x7fd35c000018 s=0x7fd35c000018 a=0x7fd35ffffef8
 lo=0x7fd35c000018 hi=0x7fd35c000018 f=0x7fd35ffffe18 s=0x7fd35ffffe08 a=0x7fd35c000018
 lo=0x7fd35ffffe30 hi=0x0 f=0x7fd35c000018 s=0x7fd35c000018 a=0x7fd35ffffe30
 lo=0x7fd35c000018 hi=0x7fd35c000018 f=0x7fd35ffffda0 s=0x7fd35ffffd90 a=0x7fd35c000018
 lo=0x7fd35ffffdb8 hi=0x0 f=0x7fd35c000018 s=0x7fd35c000018 a=0x7fd35ffffdb8
```

**Comment by eamsden** [comment]
@ashelkovnykov "the branch was force-pushed or updated" error when I try to re-open, a new PR must be made I guess

**Comment by eamsden** [comment]
Or must it?

**Pull request closed without merging**
