### PR TITLE
jets: add `trip`

### PR DESCRIPTION
**Pull request by matthew-levan**

### CODE REVIEW

**Review by eamsden — CHANGES_REQUESTED** [review]
I don't think this is necessary, it's just a special case of the `+rip` jet.

**Comment by matthew-levan** [comment]
Sounds good, wonder why it's jetted in Vere though.

**Comment by eamsden** [comment]
Even if it's unjetted, as long as there are jets for the actual bit-mashing operations it should be fine.

**Comment by joemfb** [comment]
Lots of things are jetted in vere just to provide the api to other code -- once we've written the function, might as well wire up the jet too. (`+need` is probably the best example of this.)

**Comment by matthew-levan** [comment]
Ah, that makes sense. Thanks. If we need `crate::jets::util::trip` for
another jet down the line, we can restore this branch I guess.

**Pull request closed without merging**
